import { createSupabaseContext } from '../lib/supabaseContext.ts';

Deno.serve(async (req) => {
  try {
    const { supabase, supabaseAdmin, entities, adminEntities, integrations, getUser } = createSupabaseContext(req);
    const user = await getUser();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { petition_id } = await req.json();
    if (!petition_id) return Response.json({ error: 'petition_id required' }, { status: 400 });

    // Fetch petition
    const petitions = await entities.Petition.filter({ id: petition_id });
    const petition = petitions[0];
    if (!petition) return Response.json({ error: 'Petition not found' }, { status: 404 });

    // Only creator can request
    if (petition.creator_user_id !== user.id) {
      return Response.json({ error: 'Only the petition creator can request this export' }, { status: 403 });
    }

    // Fetch signatures
    const signatures = await entities.PetitionSignature.filter({ petition_id });

    // Build geographic breakdown
    const countryBreakdown = {};
    signatures.forEach(s => {
      if (s.country_code) countryBreakdown[s.country_code] = (countryBreakdown[s.country_code] || 0) + 1;
    });

    const verifiedSigs = signatures.filter(s => s.is_verified_user && !s.is_invalidated && !s.has_withdrawn);
    const confirmedSigs = signatures.filter(s => s.is_email_confirmed && !s.is_invalidated && !s.has_withdrawn);
    const verificationRate = signatures.length > 0 ? Math.round((verifiedSigs.length / signatures.length) * 100) : 0;

    const now = new Date().toUTCString();

    const geoList = Object.entries(countryBreakdown)
      .sort(([, a], [, b]) => b - a)
      .map(([country, count]) => `  ${country}: ${count} signatures (${Math.round((count / signatures.length) * 100)}%)`)
      .join('\n') || '  No geographic data available';

    const verifiedList = verifiedSigs.slice(0, 500).map((sig, idx) =>
      `  ${idx + 1}. User ID: ${sig.user_id} | Country: ${sig.country_code || 'Unknown'} | Signed: ${new Date(sig.created_date).toUTCString()}`
    ).join('\n') || '  No verified user signatures.';

    const reportText = `
OFFICIAL PETITION EXPORT REPORT
Voice to Action Platform
Generated: ${now}
=======================================================

PETITION DETAILS
----------------
Title: ${petition.title}
Category: ${petition.category?.replace(/_/g, ' ').toUpperCase()}
Status: ${petition.status?.toUpperCase()}
Visibility: ${petition.visibility}
Created: ${new Date(petition.created_date).toUTCString()}
Deadline: ${petition.deadline ? new Date(petition.deadline).toUTCString() : 'None set'}
Creator User ID: ${petition.creator_user_id}

SHORT SUMMARY
-------------
${petition.short_summary}

FULL DESCRIPTION
----------------
${petition.full_description}

TARGET INFORMATION
------------------
Target Type: ${petition.target_type?.replace(/_/g, ' ')}
Target Organisation: ${petition.target_name}
${petition.target_contact_name ? `Contact Person: ${petition.target_contact_name}` : ''}
${petition.target_contact_email ? `Contact Email: ${petition.target_contact_email}` : ''}
Country: ${petition.country_code}
Region: ${petition.region_code || 'National/All regions'}

SPECIFIC ACTION REQUESTED
--------------------------
${petition.requested_action}

LEGAL & POLICY REFERENCE
--------------------------
${petition.legal_policy_reference || 'Not specified'}

OUTCOME CRITERIA
-----------------
${petition.outcome_criteria || 'Not specified'}

CREATOR RELATIONSHIP TO ISSUE
-------------------------------
${petition.creator_relationship || 'Not specified'}

URGENCY LEVEL
--------------
${petition.urgency_level?.replace(/_/g, ' ').toUpperCase() || 'Standard'}

SIGNATURE STATISTICS
---------------------
Total Signatures: ${(petition.signature_count_total || 0).toLocaleString()}
Verified User Signatures: ${verifiedSigs.length.toLocaleString()}
Email-Confirmed Signatures: ${confirmedSigs.length.toLocaleString()}
Verification Rate: ${verificationRate}%
Signature Goal: ${(petition.signature_goal || 0).toLocaleString()}
Progress: ${petition.signature_goal > 0 ? Math.round(((petition.signature_count_total || 0) / petition.signature_goal) * 100) : 0}%

GEOGRAPHIC BREAKDOWN
---------------------
${geoList}

VERIFIED SIGNATURE LIST (First 500)
-------------------------------------
${verifiedList}

=======================================================
This petition report was generated by Voice to Action.
Platform Owner: Jeremy Kyle Whisson
Exported by: ${user.full_name} (${user.email})
Export Date: ${now}
=======================================================
    `.trim();

    // Send email to creator
    await integrations.Core.SendEmail({
      to: user.email,
      subject: `Your Petition Export: ${petition.title}`,
      body: `
<html><body style="font-family: Arial, sans-serif; color: #1e293b; max-width: 700px; margin: auto; padding: 24px;">
  <div style="background: linear-gradient(135deg, #1d4ed8, #2563eb); padding: 24px; border-radius: 12px; margin-bottom: 24px;">
    <h1 style="color: white; margin: 0; font-size: 22px;">🏛️ Petition Export Delivered</h1>
    <p style="color: #bfdbfe; margin: 8px 0 0;">Voice to Action Platform</p>
  </div>

  <p>Hi <strong>${user.full_name}</strong>,</p>
  <p>Your petition export has been generated and is included below. This document contains the full signature data and analytics for your petition.</p>

  <div style="background: #f1f5f9; border-left: 4px solid #2563eb; padding: 16px; border-radius: 8px; margin: 20px 0;">
    <h2 style="margin: 0 0 8px; font-size: 16px;">${petition.title}</h2>
    <p style="margin: 4px 0; color: #475569;"><strong>Total Signatures:</strong> ${(petition.signature_count_total || 0).toLocaleString()}</p>
    <p style="margin: 4px 0; color: #475569;"><strong>Verified Signatures:</strong> ${verifiedSigs.length.toLocaleString()}</p>
    <p style="margin: 4px 0; color: #475569;"><strong>Countries Represented:</strong> ${Object.keys(countryBreakdown).length}</p>
    <p style="margin: 4px 0; color: #475569;"><strong>Target:</strong> ${petition.target_name}</p>
  </div>

  <h3>Full Report</h3>
  <pre style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; font-size: 12px; white-space: pre-wrap; overflow-wrap: break-word;">${reportText}</pre>

  <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;">
  <p style="color: #94a3b8; font-size: 12px;">Generated ${now} · Voice to Action · Platform Owner: Jeremy Kyle Whisson</p>
</body></html>
      `,
    });

    // Log the delivery
    await entities.PetitionWithdrawal.create({
      petition_id,
      user_id: user.id,
      petition_title: petition.title,
      payment_reference: `EMAIL-DELIVERY-${Date.now()}`,
      payment_amount: 0,
      status: "export_ready",
    });

    return Response.json({ success: true, sent_to: user.email });
  } catch (err) {
    console.error('sendPetitionReport error:', err);
    return Response.json({ error: err.message }, { status: 500 });
  }
});